### ISSUE TITLE
instance.instance.setDensity is not a function

### ISSUE THREAD

**Issue by cedricdelpoux** [psychobolt/react-planck#3]
I try to update the density prop on `<Body>` and I have the error:
`instance.instance.setDensity is not a function`

It seems like there is something wrong with this line : https://github.com/psychobolt/react-planck/blob/3a4697d40718ba897b00001b7df06e038540e59a/src/Planck.component.js#L108

**Comment by cedricdelpoux** [comment]
`instance.instance` seemed to be null because the same error occurred with other methods

**Comment by psychobolt** [comment]
It seems that the bug is that the reconciler is not checking on which props exist on certain types and updating them if appropriate.

e.g. If you are setting density, that can only be applied to a fixture: https://github.com/shakiba/planck.js#tutorial
https://github.com/shakiba/planck.js/blob/8d7cec72d4e70cb29b13519ab90d5c3ae45ad3b7/lib/Fixture.js#L247

**Comment by cedricdelpoux** [comment]
No more crash if the density is applied to `Fixture`. Thanks
